
DELIMITER $$

CREATE EVENT RequestArchiveEvent1
  ON SHEDULE
      EVERY 1 DAY
      STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 21 HOUR)
  ON COMPLETION PRESERVE
DO
BEGIN
  CALL CreateArchiveRequests(60, NULL);
  CALL CreateArchiveRequestsWithInvalidDate(240, NULL);
  CALL CreateArchiveFiles();
END$$

CREATE EVENT RequestArchiveEvent2
  ON SHEDULE
      EVERY 1 DAY
      STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 22 HOUR)
  ON COMPLETION PRESERVE
DO
BEGIN
  CALL SetDeletedFileImage();
END$$

CREATE EVENT RequestArchiveEvent3
  ON SHEDULE
      EVERY 1 DAY
      STARTS (TIMESTAMP(CURRENT_DATE) + INTERVAL 23 HOUR)
  ON COMPLETION PRESERVE
DO
BEGIN
  CALL SetArchiveFlagToRequests();
END$$

DELIMITER ;
