
DELIMITER $$

CREATE TRIGGER RequestLogInsertTrigger
  AFTER INSERT ON Requests
  FOR EACH ROW
BEGIN
  INSERT INTO RequestLog (
    RequestId,
    UserId,
    Owner,
    `Application Confirmation ID`,
    `Request Date`,
    `Approval Date`,
    Status,
    `Approval ID`,
    `Arrival Date`,
    Assigned,
    `Assignee Group`,
    Assignees,
    Immediate,
    AssignedHistory,
    `Travel Type`,
    `Exemption Category`,
    Purpose,
    `CISA Sub Category`,
    `Details`,
    `Project Document 1`,
    `Project Document 1 Reviewed?`,
    `Project Document 2`,
    `Project Document 2 Reviewed?`,
    `Proof of Port of Embarkation`,
    `Proof of Port of Embarkation Reviewed?`,
    `PCS Orders`,
    `PCS Orders Reviewed?`,
    `Letter From Medical Provider`,
    `Letter From Medical Provider Reviewed?`,
    `Nucleic Acid Amplification Test`,
    `Nucleic Acid Amplification Test Reviewed?`,
    `Requestor`,
    `Requestor Name`,
    `Requestor Email`,
    `Generating Base Email?`,
    `Sending Received?`,
    `Sending Updates?`,
    `Sending Processing?`,
    CreatedAt,
    UpdatedAt,
    UpdatedBy
  )
  VALUES (
    NEW.RequestId,
    NEW.UserId,
    NEW.Owner,
    NEW.`Application Confirmation ID`,
    NEW.`Request Date`,
    NEW.`Approval Date`,
    NEW.Status,
    NEW.`Approval ID`,
    NEW.`Arrival Date`,
    NEW.Assigned,
    NEW.`Assignee Group`,
    NEW.Assignees,
    NEW.Immediate,
    NEW.AssignedHistory,
    NEW.`Travel Type`,
    NEW.`Exemption Category`,
    NEW.Purpose,
    NEW.`CISA Sub Category`,
    NEW.`Details`,
    NEW.`Project Document 1`,
    NEW.`Project Document 1 Reviewed?`,
    NEW.`Project Document 2`,
    NEW.`Project Document 2 Reviewed?`,
    NEW.`Proof of Port of Embarkation`,
    NEW.`Proof of Port of Embarkation Reviewed?`,
    NEW.`PCS Orders`,
    NEW.`PCS Orders Reviewed?`,
    NEW.`Letter From Medical Provider`,
    NEW.`Letter From Medical Provider Reviewed?`,
    NEW.`Nucleic Acid Amplification Test`,
    NEW.`Nucleic Acid Amplification Test Reviewed?`,
    NEW.`Requestor`,
    NEW.`Requestor Name`,
    NEW.`Requestor Email`,
    NEW.`Generating Base Email?`,
    NEW.`Sending Received?`,
    NEW.`Sending Updates?`,
    NEW.`Sending Processing?`,
    NEW.CreatedAt,
    NEW.UpdatedAt,
    NEW.UpdatedBy
  );
END$$

CREATE TRIGGER RequestLogUpdateTrigger
  AFTER UPDATE ON Requests
  FOR EACH ROW
BEGIN
  INSERT INTO RequestLog (
    RequestId,
    UserId,
    Owner,
    `Application Confirmation ID`,
    `Request Date`,
    `Approval Date`,
    Status,
    `Approval ID`,
    `Arrival Date`,
    Assigned,
    `Assignee Group`,
    Assignees,
    Immediate,
    AssignedHistory,
    `Travel Type`,
    `Exemption Category`,
    Purpose,
    `CISA Sub Category`,
    `Details`,
    `Project Document 1`,
    `Project Document 1 Reviewed?`,
    `Project Document 2`,
    `Project Document 2 Reviewed?`,
    `Proof of Port of Embarkation`,
    `Proof of Port of Embarkation Reviewed?`,
    `PCS Orders`,
    `PCS Orders Reviewed?`,
    `Letter From Medical Provider`,
    `Letter From Medical Provider Reviewed?`,
    `Nucleic Acid Amplification Test`,
    `Nucleic Acid Amplification Test Reviewed?`,
    `Requestor`,
    `Requestor Name`,
    `Requestor Email`,
    `Generating Base Email?`,
    `Sending Received?`,
    `Sending Updates?`,
    `Sending Processing?`,
    CreatedAt,
    UpdatedAt,
    UpdatedBy
  )
  VALUES (
    NEW.RequestId,
    NEW.UserId,
    NEW.Owner,
    NEW.`Application Confirmation ID`,
    NEW.`Request Date`,
    NEW.`Approval Date`,
    NEW.Status,
    NEW.`Approval ID`,
    NEW.`Arrival Date`,
    NEW.Assigned,
    NEW.`Assignee Group`,
    NEW.Assignees,
    NEW.Immediate,
    NEW.AssignedHistory,
    NEW.`Travel Type`,
    NEW.`Exemption Category`,
    NEW.Purpose,
    NEW.`CISA Sub Category`,
    NEW.`Details`,
    NEW.`Project Document 1`,
    NEW.`Project Document 1 Reviewed?`,
    NEW.`Project Document 2`,
    NEW.`Project Document 2 Reviewed?`,
    NEW.`Proof of Port of Embarkation`,
    NEW.`Proof of Port of Embarkation Reviewed?`,
    NEW.`PCS Orders`,
    NEW.`PCS Orders Reviewed?`,
    NEW.`Letter From Medical Provider`,
    NEW.`Letter From Medical Provider Reviewed?`,
    NEW.`Nucleic Acid Amplification Test`,
    NEW.`Nucleic Acid Amplification Test Reviewed?`,
    NEW.`Requestor`,
    NEW.`Requestor Name`,
    NEW.`Requestor Email`,
    NEW.`Generating Base Email?`,
    NEW.`Sending Received?`,
    NEW.`Sending Updates?`,
    NEW.`Sending Processing?`,
    NEW.CreatedAt,
    NEW.UpdatedAt,
    NEW.UpdatedBy
  );
END$$

CREATE TRIGGER TravelerLogInsertTrigger
  AFTER INSERT ON Travelers
  FOR EACH ROW
BEGIN
  INSERT INTO TravelerLog (
    RequestId,
    TravelerId,
    Owner,
    `First Name`,
    `Middle Name`,
    `Last Name`,
    `Exemption Category`,
    `Origin Country`,
    `Origin State`,
    `Destination Island`,
    `Arrival Date`,
    `Arrival Flight Number`,
    `Departure Date`,
    `Departure Flight Number`,
    `Phone`,
    `Quarantine Location Type`,
    `Quarantine Location Address`,
    `Travel 14Days Before Arrival`,
    `Recent Travels`,
    `Picture ID`,
    CreatedAt,
    UpdatedAt,
    UpdatedBy
  )
  VALUES (
    NEW.RequestId,
    NEW.TravelerId,
    NEW.Owner,
    NEW.`First Name`,
    NEW.`Middle Name`,
    NEW.`Last Name`,
    NEW.`Exemption Category`,
    NEW.`Origin Country`,
    NEW.`Origin State`,
    NEW.`Destination Island`,
    NEW.`Arrival Date`,
    NEW.`Arrival Flight Number`,
    NEW.`Departure Date`,
    NEW.`Departure Flight Number`,
    NEW.`Phone`,
    NEW.`Quarantine Location Type`,
    NEW.`Quarantine Location Address`,
    NEW.`Travel 14Days Before Arrival`,
    NEW.`Recent Travels`,
    NEW.`Picture ID`,
    NEW.CreatedAt,
    NEW.UpdatedAt,
    NEW.UpdatedBy
  );
END$$

CREATE TRIGGER TravelerLogUpdateTrigger
  AFTER UPDATE ON Travelers
  FOR EACH ROW
BEGIN
  INSERT INTO TravelerLog (
    RequestId,
    TravelerId,
    Owner,
    `First Name`,
    `Middle Name`,
    `Last Name`,
    `Exemption Category`,
    `Origin Country`,
    `Origin State`,
    `Destination Island`,
    `Arrival Date`,
    `Arrival Flight Number`,
    `Departure Date`,
    `Departure Flight Number`,
    `Phone`,
    `Quarantine Location Type`,
    `Quarantine Location Address`,
    `Travel 14Days Before Arrival`,
    `Recent Travels`,
    `Picture ID`,
    CreatedAt,
    UpdatedAt,
    UpdatedBy
  )
  VALUES (
    NEW.RequestId,
    NEW.TravelerId,
    NEW.Owner,
    NEW.`First Name`,
    NEW.`Middle Name`,
    NEW.`Last Name`,
    NEW.`Exemption Category`,
    NEW.`Origin Country`,
    NEW.`Origin State`,
    NEW.`Destination Island`,
    NEW.`Arrival Date`,
    NEW.`Arrival Flight Number`,
    NEW.`Departure Date`,
    NEW.`Departure Flight Number`,
    NEW.`Phone`,
    NEW.`Quarantine Location Type`,
    NEW.`Quarantine Location Address`,
    NEW.`Travel 14Days Before Arrival`,
    NEW.`Recent Travels`,
    NEW.`Picture ID`,
    NEW.CreatedAt,
    NEW.UpdatedAt,
    NEW.UpdatedBy
  );
END$$

DELIMITER ;
